-- DropForeignKey
ALTER TABLE "BANCO_DADOS" DROP CONSTRAINT "BANCO_DADOS_TX_SCP_fkey";

-- AlterTable
ALTER TABLE "BANCO_DADOS" ALTER COLUMN "TX_SCP" DROP NOT NULL;

-- AlterTable
ALTER TABLE "USUARIOS" ADD COLUMN     "TX_TKN" TEXT;

-- AddForeignKey
ALTER TABLE "BANCO_DADOS" ADD CONSTRAINT "BANCO_DADOS_TX_SCP_fkey" FOREIGN KEY ("TX_SCP") REFERENCES "project"("CD_PRO") ON DELETE SET NULL ON UPDATE CASCADE;
