-- CreateTable
CREATE TABLE "PARAMETROS" (
    "CD_PAR" SERIAL NOT NULL,
    "TP_PAR" VARCHAR(32),
    "NM_PAR" VARCHAR(32),
    "DS_PAR" VARCHAR(100),
    "STR_01" VARCHAR(1),
    "STR_02" VARCHAR(2),
    "STR_03" VARCHAR(3),
    "STR_05" VARCHAR(4),
    "STR_10" VARCHAR(10),
    "STR_20" VARCHAR(20),
    "STR_32" VARCHAR(32),
    "STR_50" VARCHAR(50),
    "STR_100" VARCHAR(100),
    "STR_200" VARCHAR(200),
    "STR_255" VARCHAR(255),
    "STR_1000" VARCHAR(1000),
    "STR_2000" VARCHAR(2000),
    "TELEFONE" VARCHAR(15),
    "CODIGO" INTEGER,
    "COD_CURTO" SMALLINT,
    "DATA" DATE,
    "NOME" VARCHAR(50),
    "NOME_GRANDE" VARCHAR(100),
    "DINHEIRO" DECIMAL(18,2),
    "QUANTIDADE" DOUBLE PRECISION,
    "VALOR_UNITARIO" DOUBLE PRECISION,
    "LOGICO" VARCHAR(1),
    "INTEIRO" INTEGER,
    "DH_CAD" TIMESTAMP(3),

    CONSTRAINT "PARAMETROS_pkey" PRIMARY KEY ("CD_PAR")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "CD_USU" VARCHAR(100) NOT NULL,
    "NM_USU" VARCHAR(100),
    "TX_SNH" VARCHAR(100),
    "TX_EML" VARCHAR(100),
    "CD_TRC_SNH" INTEGER,
    "TF_ATV" BOOLEAN,
    "DH_CAD" TIMESTAMP,
    "TP_USU" VARCHAR(1),

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("CD_USU")
);

-- CreateTable
CREATE TABLE "BANCO_DADOS" (
    "CD_BAN" SERIAL NOT NULL,
    "CD_USU" TEXT NOT NULL,
    "DS_BAN" VARCHAR(50),
    "NM_BAN" VARCHAR(50),
    "TP_BAN" VARCHAR(1),
    "NM_SRV" VARCHAR(50),
    "NM_HST" VARCHAR(50),
    "NR_PRT" INTEGER,
    "NM_USU" VARCHAR(50),
    "NM_SNH" VARCHAR(100),
    "DH_CAD" TIMESTAMP,
    "TX_OBS" VARCHAR(255),
    "NR_QTD_RTN" SMALLINT,
    "NR_QTD_RET" SMALLINT,
    "TF_ATV" VARCHAR(1),

    CONSTRAINT "BANCO_DADOS_pkey" PRIMARY KEY ("CD_BAN")
);

-- CreateTable
CREATE TABLE "BANCO_DADOS_AVISOS" (
    "CD_BAN" INTEGER NOT NULL,
    "CD_EML" SERIAL NOT NULL,
    "NM_PES" VARCHAR(50),
    "TX_EML" VARCHAR(100),
    "NM_ASS" VARCHAR(50),
    "TP_SIT_AVS" VARCHAR(100),
    "DH_CAD" TIMESTAMP,
    "CD_USU" TEXT,

    CONSTRAINT "BANCO_DADOS_AVISOS_pkey" PRIMARY KEY ("CD_BAN","CD_EML")
);

-- CreateTable
CREATE TABLE "BANCO_DADOS_ROTINAS" (
    "CD_BAN" INTEGER NOT NULL,
    "CD_RTN" VARCHAR(100) NOT NULL,
    "DH_RTN" TIMESTAMP,
    "TX_OBS" VARCHAR(255),
    "DH_CAD" TIMESTAMP,
    "CD_USU" TEXT,

    CONSTRAINT "BANCO_DADOS_ROTINAS_pkey" PRIMARY KEY ("CD_BAN","CD_RTN")
);

-- CreateTable
CREATE TABLE "ROTINAS_EXECUTADAS" (
    "CD_RTN" VARCHAR(100) NOT NULL,
    "CD_EXE_RTN" TEXT NOT NULL,
    "DH_PRV" TIMESTAMP,
    "DH_INI_RTN" TIMESTAMP,
    "DH_FIN_RTN" TIMESTAMP,
    "DH_INI_BKP" TIMESTAMP,
    "DH_FIN_BKP" TIMESTAMP,
    "DH_INI_CMP" TIMESTAMP,
    "DH_FIN_CMP" TIMESTAMP,
    "DH_INI_NUV" TIMESTAMP,
    "DH_FIN_NUV" TIMESTAMP,
    "TP_SIT" VARCHAR(1),
    "NR_TAM_ARQ" BIGINT,
    "TF_EXC_ARQ" BOOLEAN,
    "NM_ARQ" VARCHAR(100),
    "TX_OBS" BYTEA,

    CONSTRAINT "ROTINAS_EXECUTADAS_pkey" PRIMARY KEY ("CD_RTN","CD_EXE_RTN")
);

-- CreateTable
CREATE TABLE "notifications_sent" (
    "id_RTN" VARCHAR(100) NOT NULL,
    "CD_EML" INTEGER NOT NULL,
    "TX_EML" VARCHAR(100),
    "DH_ENV" TIMESTAMP,

    CONSTRAINT "notifications_sent_pkey" PRIMARY KEY ("id_RTN","CD_EML")
);

-- CreateIndex
CREATE UNIQUE INDEX "BANCO_DADOS_AVISOS_CD_EML_key" ON "BANCO_DADOS_AVISOS"("CD_EML");

-- CreateIndex
CREATE UNIQUE INDEX "BANCO_DADOS_ROTINAS_CD_RTN_key" ON "BANCO_DADOS_ROTINAS"("CD_RTN");

-- CreateIndex
CREATE UNIQUE INDEX "ROTINAS_EXECUTADAS_CD_EXE_RTN_key" ON "ROTINAS_EXECUTADAS"("CD_EXE_RTN");

-- AddForeignKey
ALTER TABLE "BANCO_DADOS" ADD CONSTRAINT "BANCO_DADOS_CD_USU_fkey" FOREIGN KEY ("CD_USU") REFERENCES "USUARIOS"("CD_USU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BANCO_DADOS_AVISOS" ADD CONSTRAINT "BANCO_DADOS_AVISOS_CD_BAN_fkey" FOREIGN KEY ("CD_BAN") REFERENCES "BANCO_DADOS"("CD_BAN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BANCO_DADOS_AVISOS" ADD CONSTRAINT "BANCO_DADOS_AVISOS_CD_USU_fkey" FOREIGN KEY ("CD_USU") REFERENCES "USUARIOS"("CD_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BANCO_DADOS_ROTINAS" ADD CONSTRAINT "BANCO_DADOS_ROTINAS_CD_BAN_fkey" FOREIGN KEY ("CD_BAN") REFERENCES "BANCO_DADOS"("CD_BAN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BANCO_DADOS_ROTINAS" ADD CONSTRAINT "BANCO_DADOS_ROTINAS_CD_USU_fkey" FOREIGN KEY ("CD_USU") REFERENCES "USUARIOS"("CD_USU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROTINAS_EXECUTADAS" ADD CONSTRAINT "ROTINAS_EXECUTADAS_CD_RTN_fkey" FOREIGN KEY ("CD_RTN") REFERENCES "BANCO_DADOS_ROTINAS"("CD_RTN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications_sent" ADD CONSTRAINT "notifications_sent_id_RTN_fkey" FOREIGN KEY ("id_RTN") REFERENCES "ROTINAS_EXECUTADAS"("CD_EXE_RTN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications_sent" ADD CONSTRAINT "notifications_sent_CD_EML_fkey" FOREIGN KEY ("CD_EML") REFERENCES "BANCO_DADOS_AVISOS"("CD_EML") ON DELETE RESTRICT ON UPDATE CASCADE;
